{% set version = "0.7.4" %}
{% set sha256 = "4c76aa98d60f955285c0cf4f4104e40a50349b10675a090bfaa4b1e908394f0a" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  fn: chemfiles-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py<3.5]
  number: 0

requirements:
  build:
    - cmake
    - toolchain
    # We need to depend on Python to be sure to have MSVC 14 available for the
    # build: https://github.com/conda/conda/wiki/VC-features
    - python  # [win]

test:
  commands:
    - true  # this was already done during the build

about:
  home: https://chemfiles.org
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/0.7.4/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
