{% set version = "0.7.3" %}
{% set sha256 = "62c34d1f4b367dc9395b42fa35cd487eda2255437e01ace7a45d556b5522be76" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  fn: chemfiles-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py<3.5]
  number: 1

requirements:
  build:
    - cmake
    - libnetcdf 4.4.*
    - toolchain
    # We need to depend on Python to be sure to have MSVC 14 available for the
    # build: https://github.com/conda/conda/wiki/VC-features
    - python  # [win]
  run:
    - libnetcdf 4.4.*

test:
  commands:
    - true  # this was already done during the build

about:
  home: https://chemfiles.github.io
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.github.io/chemfiles/latest/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
