# Chemfiles version and SHA256
{% set version = "0.10.4" %}
{% set prerelease = "" %}
{% set sha256 = "b8232ddaae2953538274982838aa6c2df87d300f7e2f80e92c171581e06325ba" %}

{% set CMAKE_INSTALL_PREFIX = "-DCMAKE_INSTALL_PREFIX=$PREFIX" %}  # [not win]
{% set CMAKE_INSTALL_PREFIX = "-DCMAKE_INSTALL_PREFIX=%PREFIX%/Library" %}  # [win]

{% set CMAKE_COMPILERS = "" %}  # [not win]
{% set CMAKE_COMPILERS = "-DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe" %}  # [win]

{% set EXTRA_FLAGS = "" %}  # [not win]
# Remove -GL from CXXFLAGS as this takes too much time and memory
{% set EXTRA_FLAGS = "-DCMAKE_CXX_FLAGS=-MD -DCMAKE_C_FLAGS=-MD" %}  # [win]

{% set CHFL_CONFIG = "-DCHFL_SYSTEM_LZMA=ON -DCHFL_SYSTEM_BZIP2=ON" %}
{% set CMAKE_CONFIG = "-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON" %}

package:
  name: chemfiles-lib
  version: {{ version }}{{ prerelease | list | reject("equalto", "-") | join }}

source:
  - fn: chemfiles-{{ version }}{{ prerelease }}.tar.gz
    url: https://github.com/chemfiles/chemfiles/archive/{{ version }}{{ prerelease }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  script: |
    cmake -G Ninja {{ CMAKE_COMPILERS }} {{ EXTRA_FLAGS }} {{ CMAKE_CONFIG }} {{ CHFL_CONFIG }} {{ CMAKE_INSTALL_PREFIX }} .
    cmake  .
    cmake --build . --config Release --target install

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bzip2
    - xz
  run:
    - libcxx >=8  # [osx]
    - bzip2
    - xz

test:
  commands:
    - test -f $PREFIX/lib/libchemfiles$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\chemfiles.dll exit 1  # [win]

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/{{ version }}/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
