# Chemfiles version and SHA256
{% set version = "0.9.0" %}
{% set prerelease = "-rc1" %}
{% set sha256 = "a3ab2280f047044f82f1bea82843ceb6099470b5e0d769e9f1d9b273d40dc849" %}

# Chemfiles test data git version and SHA256
{% set data_git = "dee3659fad8106611a9fd0f0a5ee4596f7fb869d" %}
{% set data_sha256 = "a93d7891bff2844b136163cb5ce51fe6e15d9e0ab300d1fcdf32989ee9b62c71" %}

package:
  name: chemfiles-lib
  version: {{ version }}{{ prerelease | list | reject("equalto", "-") | join }}

source:
  - fn: chemfiles-{{ version }}{{ prerelease }}.tar.gz
    url: https://github.com/chemfiles/chemfiles/archive/{{ version }}{{ prerelease }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - export-extern-templates.patch
  - url: https://github.com/chemfiles/tests-data/archive/{{ data_git }}.tar.gz
    sha256: {{ data_sha256 }}
    folder: tests/data

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - "true"  # this was already done during the build

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/0.8.0/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
