{% set version = "0.7.4" %}
{% set sha256 = "5d84192274b1beb42f590baa723b5cca8afc8a7572be5e6bd978edc8bcf7c9b8" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  fn: chemfiles-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles/archive/{{ version }}-rc2.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py<3.5]
  number: 0

requirements:
  build:
    - cmake
    - toolchain
    # We need to depend on Python to be sure to have MSVC 14 available for the
    # build: https://github.com/conda/conda/wiki/VC-features
    - python  # [win]

test:
  commands:
    - true  # this was already done during the build

about:
  home: https://chemfiles.github.io
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.github.io/chemfiles/latest/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
