{% set version = "0.8.0" %}
{% set sha256 = "7a3b7b225e4439dc3026b25366d04f241e5510b6da415adaafcfa24f517794c7" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  fn: chemfiles-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and vc<14]
  number: 1
  include_recipe: False

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - true  # this was already done during the build

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/0.8.0/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
