# Chemfiles version and SHA256
{% set version = "0.9.2" %}
{% set prerelease = "" %}
{% set sha256 = "f0a40c8934cffdc8321bed79ded4cb4de5d5366d1f503a95467e294384521e82" %}

# Chemfiles test data git version and SHA256
{% set data_git = "f72e432e1d1f449125cf1909cc0d14e05bdbcd23" %}
{% set data_sha256 = "f70cff571630256e2d2ab866ca95943abd9db66b2a41982c2ab8d3d655980861" %}

package:
  name: chemfiles-lib
  version: {{ version }}{{ prerelease | list | reject("equalto", "-") | join }}

source:
  - fn: chemfiles-{{ version }}{{ prerelease }}.tar.gz
    url: https://github.com/chemfiles/chemfiles/archive/{{ version }}{{ prerelease }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/chemfiles/tests-data/archive/{{ data_git }}.tar.gz
    sha256: {{ data_sha256 }}
    folder: tests/data

{% set CMAKE_INSTALL_PREFIX = "$PREFIX" %}  # [not win]
{% set CMAKE_INSTALL_PREFIX = "%PREFIX%/Library" %}  # [win]
{% set CMAKE_COMPILERS = "" %}  # [not win]
{% set CMAKE_COMPILERS = "-DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe" %}  # [win]
{% set CMAKE_FLAGS = "" %}  # [not win]
# Remove -GL from CXXFLAGS as this takes too much time and memory
{% set CMAKE_FLAGS = "-DCMAKE_CXX_FLAGS=-MD -DCMAKE_C_FLAGS=-MD" %}  # [win]

build:
  skip: true  # [win and vc<14]
  number: 0
  script: |
    cmake -G Ninja {{ CMAKE_COMPILERS }} {{ CMAKE_FLAGS }} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX={{ CMAKE_INSTALL_PREFIX }} .
    cmake --build . --config Release --target install -- -v

    # Build and run the tests
    cmake -E touch tests/data/{{ data_git }}
    cmake -DCHFL_BUILD_TESTS=ON -DCHFL_BUILD_DOCTESTS=OFF .
    cmake --build . --config Release -- -v
    ctest --output-on-failure -C Release

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - libcxx >=8  # [osx]

test:
  commands:
    - test -f $PREFIX/lib/libchemfiles$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\chemfiles.dll exit 1  # [win]

about:
  home: https://chemfiles.org
  license: BSD
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/{{ version }}/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
