{% set version = "0.7.1" %}
{% set sha256 = "2bc739046d952aa60882c1418388127c424be2f149829598d6ac851c0b043081" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  fn: chemfiles-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script:
    - cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX -DCHFL_ENABLE_NETCDF=ON .
    - cmake --build . --config release --target install
    - cmake -DBUILD_SHARED_LIBS=ON .
    - cmake --build . --config release --target install
    # run the tests
    - cp $RECIPE_DIR/27d89caa55e1f42cdbbed5a322b51c702066d871.tar.gz tests/
    - cmake -DCHFL_BUILD_TESTS=ON .
    - cmake --build . --config release
    - ctest --output-on-failure

requirements:
  build:
    - cmake
    - libnetcdf 4.4.*
    - toolchain
  run:
    - libnetcdf 4.4.*

test:
  commands:
    - true  # this was already done during the build

about:
  home: https://chemfiles.github.io
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.github.io/chemfiles/latest/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
