# Chemfiles version and SHA256
{% set version = "0.9.0" %}
{% set sha256 = "ba3feedbdd1e33dc690907988cb69595eb638566e12da353e07c46ebe73cfceb" %}

# Chemfiles test data git version and SHA256
{% set data_git = "c26f254cd7bff7e476bf065403fbd0a6a47fea38" %}
{% set data_sha256 = "ba3feedbdd1e33dc690907988cb69595eb638566e12da353e07c46ebe73cfceb" %}

package:
  name: chemfiles-lib
  version: {{ version }}

source:
  - fn: chemfiles-{{ version }}.tar.gz
    url: https://github.com/chemfiles/chemfiles/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - visibility-hidden.patch
  - url: https://github.com/chemfiles/tests-data/archive/{{ data_git }}.tar.gz
    sha256: {{ data_sha256 }}
    folder: tests/data

build:
  skip: true  # [win and vc<14]
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - "true"  # this was already done during the build

about:
  home: https://chemfiles.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Modern library for chemistry file reading and writing
  doc_url: https://chemfiles.org/chemfiles/0.8.0/
  dev_url: https://github.com/chemfiles/chemfiles

extra:
  recipe-maintainers:
    - luthaf
