travis:
  secure:
    BINSTAR_TOKEN: yjWPNlfgrN80xA/i4AkSbrjJgMHoaTdIVgrSLSQsGljIcUoQtzPhGuwlG1aTQx7i7O8j1LBUt0s2vxas8EkVqVrWYeM6xXT72+FidM15GQ8nahlxGHBwhCp9/3iAtz7j9y+LUPDApojx85aCYYlObfDe0HMn3buOmop0v3ROC/cfdu0HqKPGaclYFnbRbVr7i1ygW9lFj+NgzZAw9p770Dy0xuwEKRF21Xlw0+rirf16NtP8ZOwf7IATKvogPgJDsUhUN+2hmyJPsbbdw37q5gu/kwBt5pafLnH62i7/7Rjbh14Oxt4jwArEAUD6cAbcMWvy9ddcS7QVZiUjEJhxzHQGp5tpovouDMYIehkk4j0qQAggfmoDzcEcfod2t5+AdIBuy2q1CYORWoOVfBeRrqMEvqooEmFuGZpkUuIjM5r0K2zxzlSybLAmCO2qdnldml9+mrAH0/DTuFCgW6I2KCBsuRRgX7eZFPezq466ZQcbqvNndDXsB0I+p9wKOh1bSpYRd+yTO8f6bZcaLqUkyhsJde7B0aSdh91+doxZraWaYHsmB+J11aIG1hhryfqH1I106XbXy+hmgguIXm8IdAvYhFXIjrOWyB7kk7l/JfMPZ4J5mCcQ4oE962hYnmn7o9EclB4pMgOBFC8xIwNJh+ReZSvIF2m57gtzT+96NTk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
